version: 0.1.0
addons:
  - name: community
  - name: dns
  - name: dashboard
  - name: helm
  - name: helm3
  - name: argocd
  - name: cert-manager
  - name: metallb
    args: [158.220.118.47/32]
  - name: openebs

# These arguments will be set by the 'dns' addon. We set them manually to avoid
# unnecessary Kubernetes restarts while the cluster is bootstrapping.
extraKubeletArgs:
  --cluster-dns: 10.152.183.10
  --cluster-domain: cluster.local
