apiVersion: v1
kind: Secret
metadata:
  name: k8s-config-rw
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: 'git@github.com:kuba-4chain/bux-k8s-config.git'
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCsrR6iBGyPuNJHf1v0aUENyKQzFhxo7P+WYyXIyEfmMgAAAKhKL1WTSi9V
    kwAAAAtzc2gtZWQyNTUxOQAAACCsrR6iBGyPuNJHf1v0aUENyKQzFhxo7P+WYyXIyEfmMg
    AAAEDCRoStPr6adJoZIyqCmlvsx192cbmrKAhzeqjwzhRbZ6ytHqIEbI+40kd/W/RpQQ3I
    pDMWHGjs/5ZjJcjIR+YyAAAAIXJvb3RAdm1pMTUyODEwNy5jb250YWJvc2VydmVyLm5ldA
    ECAwQ=
    -----END OPENSSH PRIVATE KEY-----
